name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  fast-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v3.0.2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
          cache: yarn
      - name: Install latest NPM on Windows
        if: matrix.os == 'windows-latest'
        # See https://github.com/actions/virtual-environments/issues/4856#issuecomment-1043256330
        # and https://github.com/actions/setup-node/issues/411#issuecomment-1051084491
        run: |
          npm install -g npm@8.3.1
          npm install -g npm@latest
      - name: Install
        run: yarn && lerna bootstrap
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn coverage:fast
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.lcov
          env_vars: CI_OS,TEST_TYPE
        env:
          CI_OS: ${{ matrix.os }}
          TEST_TYPE: fast

  slow-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-20.04]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v3.0.2
      - name: Windows specific setup
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          echo 'C:\Program Files (x86)\WiX Toolset v3.11\bin' >> $GITHUB_PATH
          npm config set node-gyp "$GITHUB_WORKSPACE\node_modules\node-gyp\bin\node-gyp.js"
      - name: Linux specific setup
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository -y ppa:alexlarsson/flatpak
          sudo rm /etc/apt/sources.list.d/bazel.list
          sudo rm /etc/apt/sources.list.d/mongo*.list
          grep -l opensuse /etc/apt/sources.list.d/* | xargs sudo rm
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends snapcraft flatpak-builder elfutils
          ci/install_runtimes.sh
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
          cache: yarn
      - name: Install
        run: yarn && lerna bootstrap
      - name: Build
        run: yarn build
      - name: Test
        run: yarn coverage:slow
        env:
          DEBUG: electron-installer-snap:snapcraft
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.lcov
          env_vars: CI_OS,TEST_TYPE
        env:
          CI_OS: ${{ matrix.os }}
          TEST_TYPE: slow
