name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Node.js LTS
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: yarn

      - name: Build
        shell: bash
        run: |
          yarn
          yarn docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: js.electronforge.io
